### ISSUE TITLE
This project is no longer compatible with recent Delphi editions.

### ISSUE THREAD

**Issue by Spynux** [nunopicado/AtWS#6]
Greetings Nuno,

First, let me salute you for your commitment, which I have been following for some time now, at [www.portugal-a-programar.pt].

I'll introduce myself, my name is Antonio Cálix, and I'm a Delphi Senior Software Development Engineer.

Currently I do not work in the area of invoicing software, but the need arose at the request of an accountant friend, to develop a small module, which among other things, would be responsible for registering series of invoices in the AT.

I found your project highly educational, however for reasons of code scalability, my policy regarding external dependencies, leads me into refraining the use of third party libraries, unless when strictly necessary.

When I tried to reproduce parts of your code, I got stuck into a compilation error, that has to do with the unit:
**Soap.SOAPHTTPTrans**,

specifically with the calling convention of the method:
**TBeforePostEvent**,

previously declared as:
**(const HTTPReqResp: THTTPReqResp; Data: Pointer)**,

and currently declared as:
**(const HTTPReqResp: THTTPReqResp; Client: THTTPClient)**.

This limitation makes it impossible to compile any of these projects, in recent Delphi editions.

So, the question I would like to pose:
Being aware of this, what is your proposal to overcome it?

Kind regards

António Cálix

**Comment by nunopicado** [comment]
Hello António.
I will have to run some tests and try to compatibilize the code if possible. Time is a bit tight these days, but I'll get to it as soon as possible. Could you say in which version of Delphi have you tested it?

**Comment by Spynux** [comment]
Hi Nuno

Thanks for your prompt reply!

I am working with the latest release, Delphi 11.0 Alexandria (Version 28) edition.

From the feedback I've been able to gather among peers, this issue was first introduced with the 10.3.0 Rio (Version 26) edition.

Kind regards

António Cálix

**Comment by nunopicado** [comment]
Thanks António
I'll look into it as soon as I possibly can and update the repository accordingly.

**Comment by Spynux** [comment]
And I'd be deeply grateful.

Cheers.
